# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: ms-template
env: production
maxReplicas: 10
cpuUsage: 60

image:
  registry: chegaai.azurecr.io
  name: ms-template
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  portName: http

environment: {}

resources:
  requests:
    cpu: 250m
